docs/python-sdk/exporting.mdx
Let me know if there is anything i need to edit :)
=> fix(docs): update exporting.mdx to include nr instrumentation

packages/traceloop-sdk/pyproject.toml, packages/traceloop-sdk/traceloop/sdk/__init__.py, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
=> fix(traceloop-sdk): logging of service name in traces

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/__init__.py, packages/sample-app/sample_app/openai_streaming.py, packages/traceloop-sdk/tests/test_openai_instrumentation.py
=> fix(openai): yield chunks for streaming

packages/opentelemetry-instrumentation-transformers/opentelemetry/instrumentation/transformers/text_generation_pipeline_wrapper.py, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
Fixes https://github.com/BerriAI/litellm/issues/1160
=> Make OpenLLMetry more robust to unexpected errors

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/__init__.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/completion_wrappers.py, packages/sample-app/poetry.lock, packages/traceloop-sdk/poetry.lock, packages/traceloop-sdk/pyproject.toml
=> fix: support pydantic v1

packages/sample-app/sample_app/methods_decorated_app.py, packages/traceloop-sdk/traceloop/sdk/__init__.py, packages/traceloop-sdk/traceloop/sdk/fetcher.py
Reverts traceloop/openllmetry#253 which restores the user feedback scores feature.
=> Restore: "feat(sdk): user feedback scores"

packages/traceloop-sdk/traceloop/sdk/__init__.py, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
=> fix(sdk): support arbitrary resources

README.md
Please make sure merge this PR after https://github.com/traceloop/docs/pull/15
@nirga ^^
=> Enabled IBM Instana Support

packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/custom_llm_instrumentor.py
Reverts traceloop/openllmetry#420
This breaks our integration of LlamaIndex (FYI @alex-feel)
=> Revert "fix: support both new and legacy llama_index versions"

packages/opentelemetry-instrumentation-watsonx/poetry.lock, packages/opentelemetry-instrumentation-watsonx/pyproject.toml, packages/opentelemetry-instrumentation-watsonx/tests/conftest.py, packages/opentelemetry-instrumentation-watsonx/tests/test_generate.py
=> chore: temporarily disabled watsonx tests

packages/traceloop-sdk/poetry.lock, packages/traceloop-sdk/pyproject.toml, packages/traceloop-sdk/tests/test_workflows.py, packages/traceloop-sdk/traceloop/sdk/decorators/__init__.py
=> fix(sdk): fail gracefully if input/output is not json serializable

packages/opentelemetry-instrumentation-anthropic/pyproject.toml, packages/opentelemetry-instrumentation-bedrock/pyproject.toml, packages/opentelemetry-instrumentation-chromadb/pyproject.toml, packages/opentelemetry-instrumentation-cohere/pyproject.toml, packages/opentelemetry-instrumentation-haystack/pyproject.toml, packages/opentelemetry-instrumentation-langchain/pyproject.toml, packages/opentelemetry-instrumentation-llamaindex/pyproject.toml, packages/opentelemetry-instrumentation-openai/pyproject.toml, packages/opentelemetry-instrumentation-pinecone/pyproject.toml, packages/opentelemetry-instrumentation-qdrant/pyproject.toml, packages/opentelemetry-instrumentation-replicate/pyproject.toml, packages/opentelemetry-instrumentation-transformers/pyproject.toml, packages/opentelemetry-instrumentation-vertexai/pyproject.toml, packages/opentelemetry-instrumentation-watsonx/pyproject.toml, packages/opentelemetry-instrumentation-weaviate/pyproject.toml, packages/traceloop-sdk/pyproject.toml
=> fix: link back to repo in pyproject.toml

packages/opentelemetry-instrumentation-watsonx/README.md, packages/opentelemetry-instrumentation-watsonx/opentelemetry/instrumentation/watsonx/__init__.py, packages/opentelemetry-instrumentation-watsonx/tests/cassettes/test_generate/test_generate_text_stream.yaml, packages/opentelemetry-instrumentation-watsonx/tests/test_generate.py
Fixes https://github.com/traceloop/openllmetry/issues/551
=> fix(watsonx): Watsonx stream generate support

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/utils.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/v1/__init__.py, packages/opentelemetry-instrumentation-openai/tests/metrics/cassettes/test_openai_metrics/test_chat_streaming_metrics.yaml, packages/opentelemetry-instrumentation-openai/tests/metrics/test_openai_metrics.py
=> fix(openai): streaming metrics

packages/opentelemetry-instrumentation-anthropic/pyproject.toml, packages/opentelemetry-instrumentation-bedrock/pyproject.toml, packages/opentelemetry-instrumentation-chromadb/pyproject.toml, packages/opentelemetry-instrumentation-cohere/pyproject.toml, packages/opentelemetry-instrumentation-haystack/pyproject.toml, packages/opentelemetry-instrumentation-langchain/pyproject.toml, packages/opentelemetry-instrumentation-llamaindex/pyproject.toml, packages/opentelemetry-instrumentation-openai/pyproject.toml, packages/opentelemetry-instrumentation-pinecone/pyproject.toml, packages/opentelemetry-instrumentation-qdrant/pyproject.toml, packages/opentelemetry-instrumentation-replicate/pyproject.toml, packages/opentelemetry-instrumentation-transformers/pyproject.toml, packages/opentelemetry-instrumentation-vertexai/pyproject.toml, packages/opentelemetry-instrumentation-watsonx/pyproject.toml, packages/opentelemetry-instrumentation-weaviate/pyproject.toml
=> fix(instrumentations): add entry points to support auto-instrumentation

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/__init__.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_functions/test_open_ai_function_calls_tools.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/test_functions.py
=> fix(openai): support tool syntax

packages/opentelemetry-instrumentation-watsonx/README.md, packages/sample-app/sample_app/watsonx_flow.py
=> Added example for watsonx flow

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/__init__.py
=> Add support to the new `headers` field called `extra_headers` field in the new OpenAI SDK

packages/sample-app/sample_app/watsonx-langchain.py
=> Added an watsonx and langchain integratioin example

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/v0/__init__.py
=> fix(openai): missing metric for v0 instrumentation

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/__init__.py, packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/custom_chat_wrapper.py, packages/opentelemetry-instrumentation-langchain/poetry.lock, packages/opentelemetry-instrumentation-langchain/pyproject.toml, packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_lcel/test_anthropic.yaml, packages/opentelemetry-instrumentation-langchain/tests/conftest.py, packages/opentelemetry-instrumentation-langchain/tests/test_lcel.py
=> fix(langchain): instrument chat models

packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py, packages/opentelemetry-instrumentation-anthropic/tests/test_completion.py
=> fix(anthropic): token usage

packages/traceloop-sdk/tests/conftest.py, packages/traceloop-sdk/tests/test_sdk_initialization.py, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
=> fix(sdk): custom instruments missing parameters

packages/opentelemetry-instrumentation-bedrock/opentelemetry/instrumentation/bedrock/__init__.py, packages/opentelemetry-instrumentation-bedrock/poetry.lock, packages/opentelemetry-instrumentation-bedrock/pyproject.toml, packages/opentelemetry-instrumentation-bedrock/tests/cassettes/test_anthropic/test_anthropic_2_completion.yaml, packages/opentelemetry-instrumentation-bedrock/tests/cassettes/test_anthropic/test_anthropic_3_completion.yaml, packages/opentelemetry-instrumentation-bedrock/tests/conftest.py, packages/opentelemetry-instrumentation-bedrock/tests/test_anthropic.py, packages/opentelemetry-instrumentation-bedrock/tests/test_placeholder.py
=> fix(bedrock): support anthropic v3

packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py, packages/opentelemetry-instrumentation-anthropic/poetry.lock, packages/opentelemetry-instrumentation-anthropic/pyproject.toml, packages/opentelemetry-instrumentation-anthropic/tests/test_completion.py
=> fix(anthropic): prompt attribute name

packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/custom_llm_instrumentor.py
=> fix(llamaindex): proper support for custom LLMs

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/custom_chat_wrapper.py, packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/task_wrapper.py, packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/workflow_wrapper.py, packages/opentelemetry-instrumentation-langchain/tests/test_chains.py, packages/opentelemetry-instrumentation-langchain/tests/test_lcel.py
=> fix(langchain): use chain names if exist

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/v0/__init__.py
=> fix(openai): missing metrics for OpenAI v0 instrumentation

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/embeddings_wrappers.py
=> fix(openai): fix aembeddings init error

packages/traceloop-sdk/traceloop/sdk/__init__.py
=> fix(sdk): warn for reporting score when not using Traceloop

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/custom_chat_wrapper.py, packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_lcel/test_openai.yaml, packages/opentelemetry-instrumentation-langchain/tests/conftest.py, packages/opentelemetry-instrumentation-langchain/tests/test_lcel.py
=> fix(langchain): bug when retrieving messages as kwargs from model invoke

packages/opentelemetry-instrumentation-chromadb/opentelemetry/instrumentation/chromadb/wrapper.py, packages/opentelemetry-instrumentation-chromadb/tests/test_query.py
=> fix(chromadb): exception thrown when metadata isn't set

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/utils.py, packages/opentelemetry-instrumentation-openai/tests/conftest.py, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_azure/test_chat.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_azure/test_chat_async_streaming.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_azure/test_chat_content_filtering.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_azure/test_chat_streaming.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/test_azure.py, packages/sample-app/sample_app/azure_openai.py
=> fix(openai): azure filtering masked all completions

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/task_wrapper.py, packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/utils.py, packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/workflow_wrapper.py, packages/opentelemetry-instrumentation-langchain/tests/test_lcel.py, packages/traceloop-sdk/traceloop/sdk/decorators/__init__.py
=> fix(langchain): input/output reporting

packages/sample-app/sample_app/azure_openai.py, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
=> fix(sdk): do not instrument sentry requests (used internally by SDK)

packages/opentelemetry-instrumentation-pinecone/opentelemetry/instrumentation/pinecone/__init__.py
=> fix(pinecone): filter argument may be dict

packages/traceloop-sdk/traceloop/sdk/telemetry.py
=> fix(sdk): separate sentry SDK

.github/workflows/ci.yml
=> ci: use build-release as build started to fail with poetry

packages/opentelemetry-instrumentation-openai/poetry.lock, packages/opentelemetry-instrumentation-openai/pyproject.toml
=> fix(openai): relax tiktoken requirements

packages/traceloop-sdk/poetry.lock, packages/traceloop-sdk/pyproject.toml
=> fix(sdk): removed unneeded tiktoken dependency

packages/opentelemetry-instrumentation-langchain/poetry.lock, packages/opentelemetry-instrumentation-llamaindex/poetry.lock, packages/opentelemetry-instrumentation-llamaindex/pyproject.toml, packages/opentelemetry-instrumentation-openai/poetry.lock, packages/opentelemetry-instrumentation-openai/pyproject.toml, packages/opentelemetry-instrumentation-pinecone/poetry.lock, packages/opentelemetry-instrumentation-weaviate/poetry.lock, packages/sample-app/poetry.lock, packages/traceloop-sdk/poetry.lock
=> fix: remove all un-needed tiktoken deps

packages/opentelemetry-instrumentation-cohere/opentelemetry/instrumentation/cohere/__init__.py, packages/opentelemetry-instrumentation-cohere/tests/test_chat.py
=> fix(cohere): use billed units for token usage

packages/traceloop-sdk/tests/cassettes/test_workflows/test_streaming_workflow.yaml, packages/traceloop-sdk/tests/conftest.py, packages/traceloop-sdk/tests/test_workflows.py, packages/traceloop-sdk/traceloop/sdk/decorators/__init__.py, packages/traceloop-sdk/traceloop/sdk/decorators/base.py, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
=> fix(sdk): handle workflow & tasks generators

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/__init__.py, packages/opentelemetry-instrumentation-openai/tests/traces/test_chat.py
=> fix(openai): report fingerprint from response

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/sample-app/sample_app/methods_decorated_app.py
=> fix(openai): old streaming handling for backward compatibility with OpenAI v0

packages/traceloop-sdk/poetry.lock, packages/traceloop-sdk/pyproject.toml, packages/traceloop-sdk/traceloop/sdk/instruments.py, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
=> fix(sdk): instrument milvus

packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py
=> fix(anthropic): don't fail if can't count anthropic tokens

packages/opentelemetry-instrumentation-bedrock/opentelemetry/instrumentation/bedrock/__init__.py, packages/opentelemetry-instrumentation-bedrock/tests/cassettes/test_anthropic/test_anthropic_3_completion_complex_content.yaml, packages/opentelemetry-instrumentation-bedrock/tests/cassettes/test_anthropic/test_anthropic_3_completion_string_content.yaml, packages/opentelemetry-instrumentation-bedrock/tests/test_anthropic.py
=> fix(bedrock): support simple string in prompts

packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
=> fix(sdk): wrong package check for mistral instrumentations

packages/opentelemetry-instrumentation-cohere/tests/cassettes/test_chat/test_cohere_chat.yaml, packages/opentelemetry-instrumentation-cohere/tests/cassettes/test_completion/test_cohere_completion.yaml, packages/opentelemetry-instrumentation-cohere/tests/cassettes/test_rerank/test_cohere_rerank.yaml
=> chore(cohere): fix tests

packages/opentelemetry-instrumentation-bedrock/opentelemetry/instrumentation/bedrock/__init__.py, packages/opentelemetry-instrumentation-bedrock/opentelemetry/instrumentation/bedrock/streaming_wrapper.py, packages/opentelemetry-instrumentation-bedrock/tests/cassettes/test_anthropic/test_anthropic_3_completion_streaming.yaml, packages/opentelemetry-instrumentation-bedrock/tests/test_anthropic.py
=> fix(bedrock): support streaming API

packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_lcel/test_async_streaming.yaml, packages/opentelemetry-instrumentation-langchain/tests/test_lcel.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py
=> fix(openai): async streaming responses

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_chat/test_chat_tools.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_chat/test_chat_tools_async_streaming.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_chat/test_chat_tools_streaming.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/test_chat.py
Fixes https://github.com/traceloop/openllmetry/issues/1283
=> feat(instrumentation): add streamed OpenAI function tracing

packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py
=> fix(anthropic): duplicate creation of metrics

packages/traceloop-sdk/tests/test_workflows.py, packages/traceloop-sdk/traceloop/sdk/decorators/base.py
=> fix(sdk): reusing generator of workflow responses

packages/traceloop-sdk/tests/test_workflows.py, packages/traceloop-sdk/traceloop/sdk/decorators/base.py
=> fix(sdk): clear context when @workflow or @task is ending

packages/traceloop-sdk/tests/test_association_properties.py, packages/traceloop-sdk/tests/test_nested_tasks.py, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
=> fix(sdk): backpropagate association property to nearest workflow/task

packages/traceloop-sdk/traceloop/sdk/__init__.py
=> fix(sdk): remove auto-create dashboard option

packages/opentelemetry-instrumentation-llamaindex/poetry.lock, packages/opentelemetry-instrumentation-llamaindex/pyproject.toml
=> chore(llamaindex): fix tests

packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py, packages/traceloop-sdk/traceloop/sdk/utils/package_check.py
=> fix(sdk): speedup SDK initialization

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/opentelemetry-instrumentation-openai/tests/traces/test_functions.py
- [x PR name follows conventional commits format: `feat(instrumentation): ...` or `fix(instrumentation): ...`.
=> refactor(openai): rename `function_call` to `tool_calls`

packages/traceloop-sdk/traceloop/sdk/decorators/base.py, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
=> fix(sdk): context detach issues on fastapi

packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
=> fix(sdk): llamaindex instrumentation was never initialized

packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/base_agent_instrumentor.py, packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/base_retriever_instrumentor.py, packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/base_synthesizer_instrumentor.py, packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/base_tool_instrumentor.py, packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/query_pipeline_instrumentor.py, packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/retriever_query_engine_instrumentor.py, packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/utils.py
=> fix(llamaindex): report inputs+outputs on entities

packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py, packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/config.py, packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/utils.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/__init__.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/__init__.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/config.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/embeddings_wrappers.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/image_gen_wrappers.py, packages/traceloop-sdk/traceloop/sdk/metrics/metrics.py, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
=> fix: association properties and workflow / task on metrics

packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/base_agent_instrumentor.py, packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/base_embedding_instrumentor.py, packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/base_retriever_instrumentor.py, packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/base_synthesizer_instrumentor.py, packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/base_tool_instrumentor.py, packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/query_pipeline_instrumentor.py, packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/retriever_query_engine_instrumentor.py
=> fix(llamaindex): report entity name

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_wrapper.py
=> fix(langchain): input/output values weren't respecting user config

packages/sample-app/sample_app/watsonx_generate.py
=> chore: update watsonx_generate.py

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_chat/test_chat_pydantic_based_tool_calls.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/test_chat.py
=> fix(openai): pydantic tool calls in prompt weren't serialized correctly

.github/dependabot.yml
=> chore: less dependabot spam

packages/traceloop-sdk/tests/cassettes/test_workflows/test_simple_aworkflow.yaml, packages/traceloop-sdk/tests/test_workflows.py, packages/traceloop-sdk/traceloop/sdk/decorators/__init__.py, packages/traceloop-sdk/traceloop/sdk/decorators/base.py
=> fix(sdk): aworkflow wasn't propagating workflow_name attribute

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/opentelemetry-instrumentation-openai/tests/traces/test_chat.py
=> feat(openai): add tool call id

packages/opentelemetry-instrumentation-pinecone/opentelemetry/instrumentation/pinecone/__init__.py, packages/opentelemetry-instrumentation-pinecone/poetry.lock, packages/opentelemetry-instrumentation-pinecone/pyproject.toml
=> fix(pinecone): support v5

packages/opentelemetry-instrumentation-bedrock/opentelemetry/instrumentation/bedrock/__init__.py, packages/opentelemetry-instrumentation-bedrock/tests/cassettes/test_titan/test_titan_completion.yaml, packages/opentelemetry-instrumentation-bedrock/tests/test_titan.py
=> fix(bedrock): token count for titan

packages/opentelemetry-instrumentation-bedrock/opentelemetry/instrumentation/bedrock/__init__.py
=> fix(bedrock): add model name for amazon bedrock response

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_wrapper.py, packages/sample-app/sample_app/langchain_lcel.py, packages/traceloop-sdk/tests/cassettes/test_association_properties/test_langchain_association_properties.yaml, packages/traceloop-sdk/tests/test_association_properties.py
=> fix(langchain): export metadata as association properties

.github/workflows/ci.yml
=> ci(github): add conventional commit PR validation

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/__init__.py, packages/sample-app/poetry.lock, packages/sample-app/pyproject.toml, packages/sample-app/sample_app/openai_structured_outputs.py, packages/traceloop-sdk/traceloop/sdk/utils/json_encoder.py
=> fix(openai): not given values thrown errors

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/sample-app/sample_app/openai_streaming.py
=> fix(openai): re-enabled token count for azure instances

packages/sample-app/poetry.lock, packages/sample-app/pyproject.toml, packages/sample-app/sample_app/langgraph_example.py
=> chore(sample-app): langgraph example

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/__init__.py, packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py, packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/utils.py, packages/sample-app/sample_app/langgraph_example.py
=> fix(langchain): langgraph traces were broken

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
=> fix(langchain): add missing kind property

packages/sample-app/data/sherlock/firstchapter.txt, packages/sample-app/sample_app/redis_rag_app.py, packages/traceloop-sdk/traceloop/sdk/instruments.py, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
=> feat(instrumentation): Import redis from OpenTelemetry, add redis sample rag application

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py, packages/traceloop-sdk/tests/cassettes/test_association_properties/test_langchain_and_external_association_properties.yaml, packages/traceloop-sdk/tests/test_association_properties.py
=> fix(langchain): allow external and langchain metadata

packages/sample-app/sample_app/vertexai_streaming.py, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
=> fix(sdk): wrong package check for Vertex AI

packages/traceloop-sdk/traceloop/sdk/__init__.py
=> fix(sdk): custom image uploader

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py, packages/opentelemetry-instrumentation-langchain/tests/test_lcel.py, packages/opentelemetry-instrumentation-langchain/tests/test_llms.py
=> fix(langchain): serialize inputs and outputs with pydantic

packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py, packages/opentelemetry-instrumentation-anthropic/tests/test_completion.py
=> fix(anthropic): Replace count_tokens with usage for newer models

CONTRIBUTING.md, README.md
docs:-Fixed typo , added links for some of them , added contributors list
=> docs(readme): contributors list; links to LLM providers

packages/opentelemetry-instrumentation-langchain/tests/conftest.py
=> ci: fix flakiness in langchain tests

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
Addresses some of the issues in #2166
=> fix(langchain): various bugs and edge cases in metric exporting

packages/opentelemetry-instrumentation-bedrock/opentelemetry/instrumentation/bedrock/__init__.py, packages/opentelemetry-instrumentation-bedrock/tests/traces/cassettes/test_cohere/test_cohere_completion.yaml, packages/opentelemetry-instrumentation-bedrock/tests/traces/test_cohere.py, packages/traceloop-sdk/traceloop/sdk/__init__.py
=> fix(bedrock): cohere models failed to report prompts

packages/traceloop-sdk/traceloop/sdk/decorators/base.py
=> fix(sdk): don't serialize large jsons as inputs/outputs

packages/opentelemetry-instrumentation-vertexai/opentelemetry/instrumentation/vertexai/__init__.py, packages/sample-app/sample_app/vertexai_streaming.py
=> fix(vertex): async / streaming was missing output fields

packages/traceloop-sdk/traceloop/sdk/utils/package_check.py
=> fix(sdk): remove print

packages/opentelemetry-instrumentation-cohere/opentelemetry/instrumentation/cohere/__init__.py
=> fix(cohere): rerank exception on saving response when return_documents=True

packages/opentelemetry-instrumentation-google-generativeai/README.md
Fixes README.md for google generative ai
=> fix: update google generative AI import

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
=> fix(langchain): azure openai missing request model 

packages/sample-app/sample_app/async_anthropic_example.py, packages/sample-app/sample_app/async_anthropic_joke_streaming.py, packages/sample-app/sample_app/async_methods_decorated_app.py, packages/sample-app/sample_app/gemini.py, packages/sample-app/sample_app/openai_functions.py, packages/sample-app/sample_app/vertexai_streaming.py, packages/traceloop-sdk/tests/test_workflows.py, packages/traceloop-sdk/traceloop/sdk/decorators/__init__.py, packages/traceloop-sdk/traceloop/sdk/decorators/base.py
=> feat(sdk): combine async/sync decorators & annotations

README.md, packages/traceloop-sdk/traceloop/sdk/__init__.py
=> docs: document telemetry collection in README

packages/opentelemetry-instrumentation-cohere/opentelemetry/instrumentation/cohere/__init__.py, packages/opentelemetry-instrumentation-cohere/tests/test_chat.py, packages/opentelemetry-instrumentation-cohere/tests/test_completion.py, packages/opentelemetry-instrumentation-cohere/tests/test_rerank.py
=> fix(cohere): add response id attribute

packages/opentelemetry-instrumentation-crewai/opentelemetry/instrumentation/crewai/instrumentation.py
=> feat(crewai): Implemented histogram for crewai instrumentation

packages/opentelemetry-instrumentation-groq/opentelemetry/instrumentation/groq/utils.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/__init__.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/utils.py
Sorry I didn't check all of these checkboxes. I'm not sure what would be an accurate way to do this. It's a performance improvement, so unit-tests are not going to capture the fix, isn't it? Also, it's not a fix to a single instrumentation library, so I'm not sure about the PR name as this change touches multiple instrumentation packages.
What I can say is that before this change I get these stats [my the test repo](https://github.com/Nagasaki45/OTEL-OpenAI-performance-investigation) (more info on #2547).
- Requests per second: 1.60
- Median time per request: 35562ms
After the change.
- Requests per second: 4.62
- Median time per request: 15417ms
(the stats are not the same as in the ticket because these are from a different machine)
I'm happy to change the code and this PR as you see …
=> Check package version at import for better performance. Fix #2547

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
=> fix(langchain): sanitize metadata

packages/traceloop-sdk/traceloop/sdk/decorators/base.py
=> fix(sdk) - Fix async decorator input & output json encoder

packages/opentelemetry-instrumentation-watsonx/opentelemetry/instrumentation/watsonx/__init__.py
=> fix(instrumentation): watsonx initialize parameters

packages/opentelemetry-instrumentation-groq/opentelemetry/instrumentation/groq/__init__.py, packages/opentelemetry-instrumentation-groq/poetry.lock, packages/opentelemetry-instrumentation-groq/pyproject.toml, packages/opentelemetry-instrumentation-groq/tests/traces/cassettes/test_chat_tracing/test_chat_streaming.yaml, packages/opentelemetry-instrumentation-groq/tests/traces/conftest.py, packages/opentelemetry-instrumentation-groq/tests/traces/test_chat_tracing.py
=> fix(groq): streaming support

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
=> fix(langchain): handle errors

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
=> fix(langchain): warning with mixed metadata value types
