.github/ISSUE_TEMPLATE/bug_report.yml, packages/traceloop-sdk/pyproject.toml, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py, packages/traceloop-sdk/traceloop/sdk/utils/__init__.py
Fixes #65 
The solution is to switch to a non-batching processor for notebooks, which will "flush" every trace directly to the exporter. We should probably do something like this for local runs as well at some point.
=> fix(traceloop-sdk): flushing in notebooks

README.md, docs/python-sdk/exporting.mdx
Added the exporter config option for Dynatrace environments.
=> Update exporting.mdx to include the Dynatrace export possibility

packages/sample-app/poetry.lock, packages/sample-app/sample_app/methods_decorated_app.py, packages/traceloop-sdk/traceloop/sdk/__init__.py, packages/traceloop-sdk/traceloop/sdk/fetcher.py
Reverts traceloop/openllmetry#247
Since this uses a new API for Traceloop which is not in production yet, reverting this and will restore after the FE is ready.
=> Revert "feat(sdk): user feedback scores"

packages/traceloop-sdk/tests/conftest.py, packages/traceloop-sdk/tests/test_sdk_initialization.py, packages/traceloop-sdk/traceloop/sdk/__init__.py
This pull request fixes a problem where `app_name` and `resource_attributes` passed to the `Traceloop.init()` method were not being added to the Trace attributes because `resource_attributes` was always `None`.
The `update()` method of the `dict` is an in-place method with a return value of `None`, so there is no need to reassign the original variable.
=> fix: `resource_attributes` always being None

packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/custom_llm_instrumentor.py
Update import logic to dynamically support both new (`llama_index.core.llms`) and legacy (`llama_index.legacy.llms.custom`) versions of the `llama_index` package. This change ensures compatibility across different versions of the package by using conditional imports and adjusting `MODULE_NAME` dynamically based on the available version. This improvement enhances the flexibility and maintainability of the codebase when working with the evolving `llama_index` library.
=> feat: support both new and legacy llama_index versions

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/completion_wrappers.py
I was getting this error:
```
> complete_choice["text"] += choice.get("text") E TypeError: can only concatenate str (not "NoneType") to str
```
=> Only accumulate text if it exists

packages/opentelemetry-instrumentation-watsonx/opentelemetry/instrumentation/watsonx/__init__.py, packages/opentelemetry-instrumentation-watsonx/tests/cassettes/test_generate/test_generate.yaml, packages/opentelemetry-instrumentation-watsonx/tests/conftest.py, packages/opentelemetry-instrumentation-watsonx/tests/test_generate.py, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
issue related discussions in https://github.com/traceloop/openllmetry/issues/542
- exclude watsonx api URLs in `EXCLUDED_URLS` in traceloop-sdk tracing
- add a watson model_init span for model initialization response time.
- update test to enable local test, but will skip in CI for now, due to issue https://github.com/traceloop/openllmetry/issues/529
=> fix(watsonx): exclude http request, adding span for model initialization

packages/sample-app/sample_app/watsonx_generate.py
We have to set OTEL_EXPORTER_OTLP_INSECURE before importing watsonx packages, otherwise, some error will be pop out like following:
```
Transient error StatusCode.DEADLINE_EXCEEDED encountered while exporting traces to c13610v1.fyre.ibm.com:4317, retrying in 1s.
```
=> fix(watsonx instrumentation): Init OTEL_EXPORTER_OTLP_INSECURE before import watsonx models

packages/opentelemetry-instrumentation-anthropic/poetry.lock, packages/opentelemetry-instrumentation-anthropic/pyproject.toml, packages/opentelemetry-instrumentation-bedrock/pyproject.toml, packages/opentelemetry-instrumentation-chromadb/poetry.lock, packages/opentelemetry-instrumentation-chromadb/pyproject.toml, packages/opentelemetry-instrumentation-cohere/poetry.lock, packages/opentelemetry-instrumentation-cohere/pyproject.toml, packages/opentelemetry-instrumentation-haystack/poetry.lock, packages/opentelemetry-instrumentation-haystack/pyproject.toml, packages/opentelemetry-instrumentation-langchain/poetry.lock, packages/opentelemetry-instrumentation-langchain/pyproject.toml, packages/opentelemetry-instrumentation-llamaindex/poetry.lock, packages/opentelemetry-instrumentation-llamaindex/pyproject.toml, packages/opentelemetry-instrumentation-openai/poetry.lock, packages/opentelemetry-instrumentation-openai/pyproject.toml, packages/opentelemetry-instrumentation-pinecone/poetry.lock, packages/opentelemetry-instrumentation-pinecone/pyproject.toml, packages/opentelemetry-instrumentation-qdrant/poetry.lock, packages/opentelemetry-instrumentation-qdrant/pyproject.toml, packages/opentelemetry-instrumentation-replicate/poetry.lock, packages/opentelemetry-instrumentation-replicate/pyproject.toml, packages/opentelemetry-instrumentation-transformers/pyproject.toml, packages/opentelemetry-instrumentation-vertexai/poetry.lock, packages/opentelemetry-instrumentation-vertexai/pyproject.toml, packages/opentelemetry-instrumentation-watsonx/pyproject.toml, packages/opentelemetry-instrumentation-weaviate/poetry.lock, packages/opentelemetry-instrumentation-weaviate/pyproject.toml, packages/traceloop-sdk/poetry.lock
Attempt to fix #591 
Didn't enable for the following instrumentations since it fails the build for some reason:
* `bedrock` (`boto3`)
* `watsonx`
* `tranformers`
=> fix: auto-instrumentation support

packages/traceloop-sdk/tests/conftest.py, packages/traceloop-sdk/tests/test_sdk_initialization.py, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
Fixes #686.
If a custom span processor is specified, its `on_start` will be called after setting LLM-specific attributes.
E.g. (https://www.traceloop.com/docs/openllmetry/integrations/sentry):
```python
Traceloop.init(processor=SentrySpanProcessor(), propagator=SentryPropagator())
```
=> fix(traceloop-sdk): custom span processor's on_start is honored

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/__init__.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/config.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/v1/assistant_wrappers.py, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_assistant/test_existing_assistant.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_assistant/test_new_assistant.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_assistant/test_streaming_existing_assistant.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_assistant/test_streaming_new_assistant.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/conftest.py, packages/opentelemetry-instrumentation-openai/tests/traces/test_assistant.py, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
=> fix(openai): enrich assistant data if not available

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/__init__.py, packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/custom_llm_wrapper.py, packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/utils.py, packages/opentelemetry-instrumentation-langchain/poetry.lock, packages/opentelemetry-instrumentation-langchain/pyproject.toml, packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_lcel/test_custom_llm.yaml, packages/opentelemetry-instrumentation-langchain/tests/test_lcel.py
=> fix(langchain): support custom models

packages/traceloop-sdk/traceloop/sdk/__init__.py, packages/traceloop-sdk/traceloop/sdk/metrics/metrics.py
Relates to #251
Current
- The metrics endpoint does not have default value, it must be set by env var for now.
- It also have to be set with otlp metrics path `/v1/metrics`, unlikely to the [traces endpoint](https://github.com/traceloop/openllmetry/tree/main/packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py#L386).
```python
def init_spans_exporter(api_endpoint: str, headers: Dict[str, str]) -> SpanExporter:
if "http" in api_endpoint.lower() or "https" in api_endpoint.lower():
return HTTPExporter(endpoint=f"{api_endpoint}/v1/traces", headers=headers)
else:
return GRPCExporter(endpoint=f"{api_endpoint}", headers=headers)
```
Proposed
- Use `api_endpoint` as default of the metrics endpoint.
- Append metrics path, just like the traces endpoint.
I didn't open new issue for this just …
=> fix(traceloop-sdk): default value for metrics endpoint

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py
=> fix(openai): handle filtered content

packages/traceloop-sdk/traceloop/sdk/__init__.py
This pull request adds a reset code that was missing from the messages output when using the custom metric exporter. Prior to making this change, there was no reset output after this message, so all subsequent messages were green.
=> fix(sdk): reset the color of messages in the custom metrics exporter

packages/opentelemetry-instrumentation-watsonx/opentelemetry/instrumentation/watsonx/__init__.py
The name in the module declaration should be matched to the filepath name of the python package.
As you know, the package is displayed as `ibm-watson-machine-learning`, but in site-packages, the filepath name is `ibm_watson_machine_learning`.
```
$ pip list | grep machine
ibm-watson-machine-learning                1.0.347
$ pwd
/usr/local/lib/python3.10/site-packages
$ ls | grep machine
ibm_watson_machine_learning
ibm_watson_machine_learning-1.0.347.dist-info
```
Otherwise, the following error will happen by **resolve_path(module, name)** call:
```
wrap_function_wrapper(
File "/Users/gyliu/new-trace/lib/python3.11/site-packages/wrapt/patches.py", line 114, in wrap_function_wrapper
return wrap_object(module, name, FunctionWrapper, (wrapper,)) …
```
=> fix(instrumentation): Correct the module declaration to match package filepath name

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/custom_chat_wrapper.py, packages/opentelemetry-instrumentation-langchain/poetry.lock, packages/opentelemetry-instrumentation-langchain/pyproject.toml, packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_lcel/test_anthropic.yaml, packages/opentelemetry-instrumentation-langchain/tests/test_chains.py, packages/opentelemetry-instrumentation-langchain/tests/test_lcel.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/sample-app/poetry.lock, packages/sample-app/pyproject.toml, packages/sample-app/sample_app/langchain_lcel.py
=> fix(langchain): support model-specific packages

packages/traceloop-sdk/poetry.lock, packages/traceloop-sdk/pyproject.toml, packages/traceloop-sdk/traceloop/sdk/telemetry.py
=> fix(sdk): loosen SDK requirements for Sentry + Posthog

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/opentelemetry-instrumentation-openai/tests/metrics/test_openai_metrics.py
=> fix(openai): add default value of stream as false in token usage metric

packages/traceloop-sdk/traceloop/sdk/__init__.py
If a user sets `exporter`, but not `metrics_exporter` than the metrics will try to default to Traceloop which doesn't make sense. So disabling metrics sending for this case.
=> fix(sdk): special handling for metrics with custom traces exporter

packages/opentelemetry-instrumentation-vertexai/opentelemetry/instrumentation/vertexai/__init__.py
Without this change it's impossible to tell from the traces which execution path was used (sync, async, streamed).
=> fix(vertexai): change the span names to match method calls

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py
=> fix(openai): handle empty finish_reason

packages/opentelemetry-instrumentation-haystack/opentelemetry/instrumentation/haystack/utils.py, packages/opentelemetry-instrumentation-haystack/opentelemetry/instrumentation/haystack/wrap_pipeline.py, packages/opentelemetry-instrumentation-haystack/tests/conftest.py, packages/opentelemetry-instrumentation-haystack/tests/test_simple_pipeline.py
=> fix(haystack): add input and output

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_chat/test_chat_tool_calls.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/test_chat.py
https://github.com/traceloop/openllmetry/issues/1428
=> fix(openai): Handle `tool_calls` assistant messages

packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py, packages/opentelemetry-instrumentation-bedrock/opentelemetry/instrumentation/bedrock/__init__.py, packages/opentelemetry-instrumentation-google-generativeai/opentelemetry/instrumentation/google_generativeai/__init__.py, packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/__init__.py, packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_wrapper.py, packages/opentelemetry-instrumentation-langchain/tests/test_chains.py, packages/opentelemetry-instrumentation-langchain/tests/test_documents_chains.py, packages/opentelemetry-instrumentation-langchain/tests/test_lcel.py, packages/opentelemetry-instrumentation-mistralai/opentelemetry/instrumentation/mistralai/__init__.py, packages/opentelemetry-instrumentation-ollama/opentelemetry/instrumentation/ollama/__init__.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/completion_wrappers.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/embeddings_wrappers.py, packages/opentelemetry-instrumentation-transformers/opentelemetry/instrumentation/transformers/text_generation_pipeline_wrapper.py, packages/opentelemetry-instrumentation-vertexai/opentelemetry/instrumentation/vertexai/__init__.py, packages/traceloop-sdk/poetry.lock, packages/traceloop-sdk/pyproject.toml, packages/traceloop-sdk/tests/test_tasks.py
Fixes #1395, #1297
Instead of relying on the SDKs instrumentations when using LangChain, we should use the fact that frameworks like LangChain and LlamaIndex know about the LLM calls and all the details and already provide them in a standard format. This PR starts reporting LLM calls here and suppresses those reports in the LLM-specific instrumentations.
cc: @tibor-reiss
=> fix(langchain): report llm spans (instead of normal instrumentations)

packages/traceloop-sdk/traceloop/sdk/__init__.py, packages/traceloop-sdk/traceloop/sdk/fetcher.py
Fixes #1820 
In order to address #1820, I've disabled traceloop sync by default. The problem is that we have 2 types of users:
1. Users who only use Traceoop for tracing - and for them the fact that an invalid key was provided shouldn't make the app crash (since it's just the observability that's not working)
2. Users who use Traceloop for tracing + prompt mgmt - and for them the fact that an invalid API key was provided means they can't fetch prompts - so app should fail to start (cause it can't operate properly without an API key).
So I think it's best to assume users are of group 1, and need to explicitly state that they are in group 2 by enabling traceloop sync. We'll update the docs to reflect that.
=> fix(sdk): disable traceloop sync by default

packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
With the traceloop-sdk since https://github.com/traceloop/openllmetry/pull/1374, the instrumentation cannot work for watsonx because of incorrect package name.
Actually the new `ibm_watsonx_ai` Python SDK is upgraded version of ibm_watson_machine_learning. They are similar in usage, anyway, it's better to check the both two SDKs.
```python
def is_package_installed(package_name: str) -> bool:
print("Packages: ", installed_packages)  # Debug output for checking package name.
return package_name in installed_packages
```
**Debug output:**
Packages: {'requests', 'packaging', 'opentelemetry-instrumentation-chromadb', 'langchain-ibm', 'jiter', 'distro', 'langsmith', 'importlib-metadata', 'ibm-watsonx-ai', 'googleapis-common-protos', 'opentelemetry-instrumentation-langchain', 'backoff', …
=> Correct the package names for watsonx

packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py, packages/opentelemetry-instrumentation-anthropic/tests/test_completion.py
Solves #1944 
This fix ignores token counting for images. Therefore, price calculated based on this one will be missing the vision part.
=> fix(anthropic): token counting exception when prompt contains images

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py, packages/opentelemetry-instrumentation-langchain/poetry.lock, packages/opentelemetry-instrumentation-langchain/tests/test_chains.py, packages/opentelemetry-instrumentation-langchain/tests/test_lcel.py, packages/opentelemetry-instrumentation-langchain/tests/test_llms.py
=> fix(langchain): token usage reporting

packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/dispatcher_wrapper.py, packages/opentelemetry-instrumentation-llamaindex/tests/test_agents.py
Set LLM_REQUEST_TYPE attribute to span for tracking chat requests. This change ensures proper monitoring and categorization. (#XYZ-123)
=> fix(llama-index): add attribute to span for llm request type in dispatcher wrapper

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/v1/__init__.py, packages/opentelemetry-instrumentation-openai/poetry.lock, packages/opentelemetry-instrumentation-openai/pyproject.toml, packages/opentelemetry-instrumentation-openai/tests/metrics/cassettes/test_openai_metrics/test_chat_parsed_completion_metrics.yaml, packages/opentelemetry-instrumentation-openai/tests/metrics/test_openai_metrics.py, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_structured/test_async_parsed_completion.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_structured/test_async_parsed_refused_completion.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_structured/test_parsed_completion.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_structured/test_parsed_refused_completion.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/test_structured.py
Fixes https://github.com/traceloop/openllmetry/issues/1815. I'm not sure if the [response_format](https://opentelemetry.io/docs/specs/semconv/attributes-registry/gen-ai/#openai-attributes) span attribute should be added in this PR as well.
Also, the metrics tests are a bit fragile since each executed test adds its metrics to the `reader.get_metrics_data()` result, so figuring out what was added is a bit tricky.
=> fix(openai): add structured output instrumentation

packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py, packages/opentelemetry-instrumentation-anthropic/poetry.lock, packages/opentelemetry-instrumentation-anthropic/pyproject.toml, packages/opentelemetry-instrumentation-anthropic/tests/cassettes/test_completion/test_anthropic_tools.yaml, packages/opentelemetry-instrumentation-anthropic/tests/test_completion.py
This commit addresses [#879] by implementing instrumentation of Anthropic `tools` request args and `tool_use` response arguments.
=> fix(anthropic): add instrumentation for Anthropic tool calling (alternative to #1372)

packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/__init__.py, packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py, packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_agents/test_agents.yaml, packages/opentelemetry-instrumentation-langchain/tests/conftest.py, packages/opentelemetry-instrumentation-langchain/tests/metrics/cassettes/test_langchain_metrics/test_llm_chain_metrics.yaml, packages/opentelemetry-instrumentation-langchain/tests/metrics/cassettes/test_langchain_metrics/test_llm_chain_streaming_metrics.yaml, packages/opentelemetry-instrumentation-langchain/tests/metrics/test_langchain_metrics.py, packages/opentelemetry-instrumentation-langchain/tests/test_agents.py
=> fix(langchain): metrics support

packages/traceloop-sdk/traceloop/sdk/__init__.py, packages/traceloop-sdk/traceloop/sdk/logging/logging.py
The headers could be needed for LogExporter to connect to some logs receivers.
If no TRACELOOP_LOGGING_HEADERS defined, the TRACELOOP_HEADERS will be used.
=> fix(sdk): add header for logging exporter

packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py, packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/utils.py, packages/opentelemetry-instrumentation-anthropic/tests/cassettes/test_completion/test_with_asyncio_run.yaml, packages/opentelemetry-instrumentation-anthropic/tests/test_completion.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py, packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/utils.py, packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_chat/test_with_asyncio_run.yaml, packages/opentelemetry-instrumentation-openai/tests/traces/test_chat.py
fixes: https://github.com/traceloop/openllmetry/issues/2195
=> fix(openai+anthropic): async call crashing the app when already in a running asyncio loop

packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
Also re-ordered instrumentations in alphabetical order.
=> fix(sdk): missing sagemaker initialization

packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
=> fix(sdk): gemini instrumentation was never installed due to package name error

packages/traceloop-sdk/tests/test_class_tasks.py, packages/traceloop-sdk/traceloop/sdk/utils/json_encoder.py
I noticed that when using the task decorator on class instance methods, the `traceloop.entity.input` attribute was not showing up in spans. I did some digging and saw that a TypeError was being triggered when trying to [serialize the methods args](https://github.com/traceloop/openllmetry/blob/b7d917ffbbe856e0ccb56f271860bac8e462c161/packages/traceloop-sdk/traceloop/sdk/decorators/base.py#L68) because the first arg is the instance of the class. 
To fix this issue, I've made an update to the custom `JSONEncoder` to properly handle class instances. Specifically, if the encoder encounters an object that cannot be directly serialized, it now falls back to returning the class’s name as a string.
=> fix(sdk): Update JSONEncoder to allow class instance methods to be serializable

packages/traceloop-sdk/traceloop/sdk/__init__.py, packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
=> fix(sdk): option to disable SDK

packages/opentelemetry-instrumentation-groq/opentelemetry/instrumentation/groq/__init__.py, packages/opentelemetry-instrumentation-groq/tests/traces/test_chat_tracing.py
=> fix(groq): add response id attribute

packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/__init__.py
=> fix(openai): don't eagerly import types from openai as they may not be available

packages/traceloop-sdk/traceloop/sdk/utils/package_check.py
=> fix(sdk): improve package name detection for metadata

packages/traceloop-sdk/traceloop/sdk/utils/package_check.py
=> fix(sdk): improve package name detection with type hints and null safety

packages/opentelemetry-instrumentation-bedrock/opentelemetry/instrumentation/bedrock/__init__.py, packages/opentelemetry-instrumentation-bedrock/tests/traces/cassettes/test_anthropic/test_anthropic_cross_region.yaml, packages/opentelemetry-instrumentation-bedrock/tests/traces/cassettes/test_nova/test_nova_cross_region_invoke.yaml, packages/opentelemetry-instrumentation-bedrock/tests/traces/test_anthropic.py, packages/opentelemetry-instrumentation-bedrock/tests/traces/test_nova.py
This PR add supports for correctly tracing model invoked via direct ARN or cross-region endpoint.
Relevant docs: 
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/bedrock-runtime/client/invoke_model.html
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/bedrock-runtime/client/converse.html#
- x-region endpoints list: https://docs.aws.amazon.com/bedrock/latest/userguide/inference-profiles-support.html#inference-profiles-support-system
=> feat(bedrock): add support for ARN and cross region endpoint

packages/opentelemetry-instrumentation-mcp/opentelemetry/instrumentation/mcp/instrumentation.py
This PR aims to add trace status for failed error calls. This helps in grouping error calls by nature of failures.
=> fix(MCP): Added error status to traces in MCP server for tool calls

.github/workflows/ci.yml, .github/workflows/release.yml
Reverts traceloop/openllmetry#3288
=> Revert "chore(ci): reduce disk space usage"
